<?php
return [

    'blog_posts' => [
        'index' => 'List blog posts',
        'create' => 'Create blog posts',
        'edit' => 'Edit blog posts',
        'destroy' => 'Destroy blog posts',
        'active' => 'Active Post',
    ],
    'blog_categories' => [
        'index' => 'List categories',
        'create' => 'Create categories',
        'edit' => 'Edit categories',
        'destroy' => 'Destroy categories',
        'active' => 'Active Category',
    ],
    'blog_tags' => [
        'index' => 'List blog tags',
        'create' => 'Create blog tags',
        'edit' => 'Edit blog tags',
        'destroy' => 'Destroy blog tags',
        'active' => 'Active',
    ],

    'user' => [
        'index' => 'List User',
        'create' => 'Create User',
        'edit' => 'Edit User',
        'destroy' => 'Destroy user',
        'changeLang' => 'Change Language',
        'active' => 'Active',
    ],
    'role' => [
        'index' => 'List Role',
        'create' => 'Create Role',
        'edit' => 'Edit Role',
        'destroy' => 'Destroy Role',
        'active' => 'Active',
    ],
    'banner' => [
        'index' => 'List Banner',
        'create' => 'Create Banner',
        'edit' => 'Edit Banner',
        'destroy' => 'Destroy Banner',
        'active' => 'Active',
    ],
    'widget' => [
        'index' => 'List Widget',
        'create' => 'Create Widget',
        'edit' => 'Edit Widget',
        'destroy' => 'Destroy Widget',
        'active' => 'Active',
    ],
    'discount' => [
        'index' => 'List discount',
        'create' => 'Create discount',
        'edit' => 'Edit discount',
        'destroy' => 'Destroy discount',
        'active' => 'Active',
    ],
    'page' => [
        'index' => 'List pages',
        'create' => 'Create pages',
        'edit' => 'Edit pages',
        'destroy' => 'Destroy pages',
        'active' => 'Active',
    ],
    'address' => [
        'index' => 'List address',
        'create' => 'Create address',
        'edit' => 'Edit address',
        'destroy' => 'Destroy address',
        'active' => 'Active',
    ],
    'product_tags' => [
        'index' => 'List address',
        'create' => 'Create address',
        'edit' => 'Edit address',
        'destroy' => 'Destroy address',
        'active' => 'Active',
    ],

    'contact' => [
        'index' => 'List contact',
        'create' => 'Create contact',
        'edit' => 'Edit contact',
        'destroy' => 'Destroy contact',
        'active' => 'Active',
    ],
    'product_products' => [
        'index' => 'List product_products',
        'create' => 'Create product_products',
        'edit' => 'Edit product_products',
        'destroy' => 'Destroy product_products',
        'active' => 'Active',
    ],

    'product_category' => [
        'index' => 'List product category',
        'create' => 'Create product category',
        'edit' => 'Edit product category',
        'destroy' => 'Destroy product category',
        'active' => 'Active',
    ],

    'qa_question' => [
        'index' => 'List Question',
        'create' => 'Create Question',
        'edit' => 'Edit Question',
        'destroy' => 'Destroy Question',
        'active' => 'Active',
    ],
    'translate' => [
        'index' => 'List translate',
        'edit' => 'Edit translate',
        'destroy' => 'Destroy translate',
    ],
    'qa_answer' => [
        'index' => 'List Answer',
        'create' => 'Create Answer',
        'edit' => 'Edit Answer',
        'destroy' => 'Destroy Answer',
        'active' => 'Active',
    ],

    'event' => [
        'index' => 'List event',
        'create' => 'Create event',
        'edit' => 'Edit event',
        'destroy' => 'Destroy event',
        'active' => 'Active',
    ],
    'course_category' => [
        'index' => 'List course_categories',
        'create' => 'Create course_categories',
        'edit' => 'Edit course_categories',
        'destroy' => 'Destroy course_categories',
        'active' => 'Active',
    ],
    'course_courses' => [
        'index' => 'List course',
        'create' => 'Create course',
        'edit' => 'Edit course',
        'destroy' => 'Destroy course',
        'active' => 'Active',
    ],
    'notification' => [
        'index' => 'List notification',
        'create' => 'Create notification',
        'edit' => 'Edit notification',
        'destroy' => 'Destroy notification',
        'active' => 'Active',
    ],
    'chapter' => [
        'index' => 'List chapter',
        'create' => 'Create chapter',
        'edit' => 'Edit chapter',
        'destroy' => 'Destroy chapter',
        'active' => 'Active',
    ],
    'lesson' => [
        'index' => 'List lesson',
        'create' => 'Create lesson',
        'edit' => 'Edit lesson',
        'destroy' => 'Destroy lesson',
        'active' => 'Active',
    ],
    'bank' => [
        'index' => 'List bank',
        'create' => 'Create bank',
        'edit' => 'Edit bank',
        'destroy' => 'Destroy bank',
        'active' => 'Active',
    ],
    'partner' => [
        'index' => 'List partner',
        'create' => 'Create partner',
        'edit' => 'Edit partner',
        'destroy' => 'Destroy partner',
        'active' => 'Active',
    ],
    'rank' => [
        'index' => 'List rank',
        'create' => 'Create rank',
        'edit' => 'Edit rank',
        'destroy' => 'Destroy rank',
        'active' => 'Active',
    ],
    'order' => [
        'index' => 'List order',
        'create' => 'Create order',
        'edit' => 'Edit order',
        'destroy' => 'Destroy order',
        'detail' => 'View detail',
        'status_course' => 'Active Course',
        'active' => 'Active',
    ],
    'warehouse' => [
        'index' => 'List warehouse',
        'create' => 'Create warehouse',
        'edit' => 'Edit warehouse',
        'destroy' => 'Destroy warehouse',
        'active' => 'Active',
    ],
    'size' => [
        'index' => 'List size product',
        'create' => 'Create size product',
        'edit' => 'Edit size product',
        'destroy' => 'Destroy size product',
        'active' => 'Active',
    ],
    'color' => [
        'index' => 'List color product',
        'create' => 'Create color product',
        'edit' => 'Edit color product',
        'destroy' => 'Destroy color product',
        'active' => 'Active',
    ],
    'ship_fee_district' => [
        'index' => 'List phí ship',
        'create' => 'Create phí ship',
        'edit' => 'Edit phí ship',
        'destroy' => 'Destroy phí ship',
        'active' => 'Active',
    ],
    'coupon' => [
        'index' => 'List coupon',
        'create' => 'Create coupon',
        'edit' => 'Edit coupon',
        'destroy' => 'Destroy coupon',
        'active' => 'Active',
    ],
    'pages_dynamic' => [
        'index' => 'List pages_dynamic',
        'create' => 'Create pages_dynamic',
        'edit' => 'Edit pages_dynamic',
        'destroy' => 'Destroy pages_dynamic',
        'active' => 'Active',
    ],
    'config' => [
        'edit' => 'Edit config',
    ],
    'logs' => [
        'index' => 'List logs',
    ],
    'customer' => [
        'index' => 'List Student',
    ],
];


?>
